name: CI TP2-Docker

on:
    # Launch this job when pushing to main or master
    push:
        branches:
            - main
            - master

    # Also launch the job for pull requests
    pull_request:

jobs:
    test-backend:
        runs-on: ubuntu-24.04

        steps:
            # Checkout your GitHub code
            - uses: actions/checkout@v4

            # Setup JDK 21
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"

            # Build and test the application with Maven
            - name: Build and test with Maven
              run: mvn clean verify
              working-directory: ./backend

    # Define job to build and publish Docker images
    build-and-push-docker-image:
        needs: test-backend
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build image and push backend
              uses: docker/build-push-action@v6
              with:
                  context: ./backend
                  tags: ${{ secrets.DOCKER_USERNAME }}/tp2-docker-devops-back:latest

            - name: Build image and push database
              uses: docker/build-push-action@v6
              with:
                  context: ./database
                  tags: ${{ secrets.DOCKER_USERNAME }}/tp2-docker-devops-db:latest

            - name: Build image and push httpd
              uses: docker/build-push-action@v6
              with:
                  context: ./httpd
                  tags: ${{ secrets.DOCKER_USERNAME }}/tp2-docker-devops-front:latest
